// English texts for the engine catalogue. Keys match catalog.js.

export const ENGINE_EN = {
  name: 'V8 5.0',
  kind: 'Naturally aspirated racing engine',
  intro: 'A 60-degree V8 built for circuit racing: high revs, dry-sump lubrication, an individual throttle for every cylinder and a titanium exhaust.',
  specs: [
    ['Type', 'petrol, naturally aspirated, V8, 60° bank angle'],
    ['Displacement', '4,999 cc'],
    ['Bore × stroke', '92.0 × 94.0 mm'],
    ['Compression ratio', '12.5 : 1'],
    ['Power', '≈ 470 kW (640 hp) at 7,500 rpm'],
    ['Torque', '≈ 610 N·m at 6,000 rpm'],
    ['Valvetrain', 'DOHC, 32 valves, chain drive'],
    ['Fuel system', 'port injection, 8 throttle bodies'],
    ['Ignition', 'individual coil on every plug'],
    ['Lubrication', 'dry sump, 4-stage pump'],
    ['Firing order', '1‑5‑4‑8‑7‑2‑6‑3'],
    ['Weight', '≈ 150 kg dry'],
  ],
  note: 'Figures are typical for racing V8s of this class. The model is an illustrative reconstruction from a photograph; part dimensions are approximate.',
};

const headAbout = side => `Closes the ${side} bank of cylinders from above. The head holds the combustion chambers, intake and exhaust ports, 16 valves and two camshafts that open each valve at exactly the right moment.`;
const exhAbout = side => `Collects exhaust gas from the four cylinders of the ${side} bank into a single pipe. Pipe lengths and diameters are chosen so that pressure waves help scavenge the cylinders.`;

export const ASM_EN = {
  block: { name: 'Cylinder block', about: 'The structural backbone of the engine. The pistons run in the block and the crankshaft turns in it; the heads, front cover, sump and accessories all bolt to it. Coolant passages and oil galleries run inside.' },
  crank: { name: 'Crank train', about: 'Turns the up-and-down motion of the pistons into crankshaft rotation. This is where combustion pressure becomes torque, which leaves through the flywheel and clutch to the gearbox.' },
  headR: { name: 'Cylinder head, right bank', about: headAbout('right') },
  headL: { name: 'Cylinder head, left bank', about: headAbout('left') },
  intake: { name: 'Intake system', about: 'Feeds air into the cylinders and meters it. Each cylinder has its own trumpet and its own throttle, so the engine responds instantly to the pedal.' },
  fuel: { name: 'Fuel system', about: 'Delivers petrol at constant pressure to eight injectors, which spray it into the intake runners in exactly the amount the control unit calculated.' },
  exhR: { name: 'Exhaust manifold, right bank', about: exhAbout('right') },
  exhL: { name: 'Exhaust manifold, left bank', about: exhAbout('left') },
  timing: { name: 'Camshaft drive', about: 'Links the crankshaft to the four camshafts. Two chains turn the cams at exactly half crankshaft speed and keep the valve timing precise at any rpm.' },
  front: { name: 'Accessory drive', about: 'The units the engine drives itself: the alternator and the water pump, both turned by a single poly-V belt from the crankshaft pulley.' },
  lube: { name: 'Dry-sump lubrication', about: 'Oil is stored in a separate tank instead of the sump. A multi-stage pump scavenges it from the crankcase and feeds it under pressure to the bearings, so lubrication stays reliable even in long corners at 2–3 g.' },
  clutch: { name: 'Flywheel and clutch', about: 'Pass torque from the crankshaft to the gearbox and let the driver disconnect them smoothly when pulling away and changing gear.' },
  elec: { name: 'Electronics and wiring', about: 'The control unit reads the sensors and calculates injection and ignition timing for every cylinder. The wiring loom connects it to the coils, injectors and sensors.' },
  ext: { name: 'Oil tank and radiator', about: 'In the car these units are mounted away from the engine; on the stand they are shown alongside it. The tank stores the dry-sump oil supply, the radiator passes coolant heat to the oncoming air.' },
};

export const PARTS_EN = {
  'block.casting': { name: 'Cylinder block', qty: '1', mat: 'Aluminium alloy, heat-treated casting',
    role: 'Holds the cylinders in exact alignment and carries combustion pressure and crankshaft loads. Every other assembly bolts to it.',
    how: 'Two banks of four cylinders sit at 60° to each other. A coolant jacket around the bores removes heat, and a main oil gallery feeds the main bearings. Ribs on the crankcase walls add stiffness without extra weight.',
    data: [['Bank angle', '60°'], ['Bore spacing', '106 mm'], ['Bank offset', '22 mm'], ['Casting weight', '≈ 38 kg']] },
  'block.liners': { name: 'Cylinder liners', qty: '8', mat: 'Aluminium with Nikasil coating (nickel + silicon carbide)',
    role: 'Form the running surface of each cylinder for the piston and rings.',
    how: 'A hard nickel–silicon-carbide layer a few hundredths of a millimetre thick barely wears and holds an oil film well. The fine cross-hatch left by honing retains oil and helps the rings bed in.',
    data: [['Bore', '92.0 mm'], ['Coating', '0.05–0.08 mm'], ['Finish', 'plateau honing']] },
  'block.mainCaps': { name: 'Main bearing caps', qty: '5', mat: 'Forged steel',
    role: 'Together with the block bulkheads they form the crankshaft bearing housings.',
    how: 'Each cap is clamped by vertical bolts and cross-bolts through the crankcase walls. This stops the housing flexing at high rpm and keeps all five bores in line.',
    data: [['Fastening', '2 vertical + 2 cross bolts'], ['Housing bore', '64 mm']] },
  'block.knock': { name: 'Knock sensors', qty: '2', mat: 'Piezo element in a steel body',
    role: 'Detect knock, an explosive combustion that can destroy pistons in seconds.',
    how: 'A piezo crystal turns block vibration into an electrical signal. The control unit picks out the knock frequency and immediately retards ignition in the cylinder where it occurred.',
    data: [['Principle', 'piezoelectric, broadband'], ['Location', 'one per bank']] },

  'crank.shaft': { name: 'Crankshaft', qty: '1', mat: 'Alloy steel forging, nitrided',
    role: 'Collects the forces from eight connecting rods and delivers torque to the flywheel and accessory drive.',
    how: 'Five main journals run in the block, and four crank throws are set at 90° (cross-plane layout). Each crankpin is split into two halves offset by 30°, so with a 60° bank angle the cylinders still fire evenly, every 90° of rotation. Counterweights balance the rotating masses.',
    data: [['Crank radius', '47 mm (94 mm stroke)'], ['Main journals', '5 × Ø60 mm'], ['Crankpins', '8 × Ø50 mm, 30° split'], ['Weight', '≈ 17 kg']] },
  'crank.rods': { name: 'Connecting rods', qty: '8', mat: 'Alloy steel, H-section',
    role: 'Link each piston to the crankshaft and carry force both ways: on the power stroke and when the piston is stopped at each dead centre.',
    how: 'The small end pivots on the piston pin; the split big end wraps the crankpin through thin bearing shells. At 7,500 rpm inertia pulls on the rod cap with about two tonnes of force, so it is clamped with high-strength bolts.',
    data: [['Centre-to-centre length', '150 mm'], ['Weight', '≈ 560 g'], ['Bearings', 'tri-metal, lead bronze']] },
  'crank.pistons': { name: 'Pistons', qty: '8', mat: 'Forged aluminium alloy, coated skirt',
    role: 'Take the gas pressure in the cylinder and pass it through the pin to the connecting rod.',
    how: 'A short skirt and thin crown save weight: at high rpm every extra gram loads the rod and bearings. The skirt carries a low-friction coating, and an oil jet cools the underside of the crown.',
    data: [['Diameter', '92.0 mm'], ['Compression height', '31 mm'], ['Weight with pin', '≈ 380 g'], ['Mean piston speed at 7,500 rpm', '23.5 m/s']] },
  'crank.rings': { name: 'Piston rings', qty: '8 sets of 3', mat: 'Nitrided steel, cast iron',
    role: 'Seal the gap between piston and cylinder: gas must not get down, oil must not get up.',
    how: 'Gas pressure pushes the top compression ring against the wall, the second ring completes the seal and scrapes off excess oil, and the oil-control ring leaves only a thin film on the bore. Racing rings are thin, about a millimetre, to reduce friction.',
    data: [['Ring heights', '1.0 / 1.2 / 2.0 mm'], ['Set', '2 compression + oil control']] },
  'crank.pins': { name: 'Piston pins', qty: '8', mat: 'Tool steel, diamond-like coating',
    role: 'Hinge the piston to the connecting rod small end.',
    how: 'The pin is fully floating: it turns freely both in the piston bosses and in the rod bush, so it wears evenly. Circlips stop it moving sideways, and the coating cuts friction and prevents scuffing.',
    data: [['Diameter', '22 mm'], ['Length', '58 mm'], ['Retention', '2 circlips']] },
  'crank.balancer': { name: 'Balance shaft', qty: '1', mat: 'Steel, eccentric weights',
    role: 'Cancels the vibration a 60° V8 produces.',
    how: 'With this bank angle the piston inertia forces add up to a rocking couple that the crank counterweights can only half cancel. A weighted shaft spinning at crank speed in the opposite direction creates an equal and opposite couple, so the engine runs smoothly and the mounts and accessories are spared.',
    data: [['Speed', 'equal to crankshaft'], ['Direction', 'counter-rotating'], ['Location', 'in the vee of the block']] },

  'head.gasket': { name: 'Head gasket', qty: '1', mat: 'Multi-layer steel with elastomer coating',
    role: 'Seals the joint between head and block: it holds combustion pressure and keeps coolant and oil apart.',
    how: 'Several thin steel layers with embossed beads around each bore act as springs and withstand combustion pressures of about 100 bar. Coolant holes are sized so that the coolant flows through the head in the intended direction.',
    data: [['Compressed thickness', '1.2 mm'], ['Layers', '3–5']] },
  'head.casting': { name: 'Cylinder head', qty: '1', mat: 'Aluminium alloy, permanent-mould casting, heat-treated',
    role: 'Forms the combustion chambers and the ports through which the mixture enters and the exhaust leaves.',
    how: 'A pent-roof chamber with four valves and a central spark plug burns the mixture quickly and completely. The ports are shaped and polished for good filling at high rpm. Valve seats and guides are pressed in from wear-resistant alloys.',
    data: [['Valves per cylinder', '4'], ['Included valve angle', '30°'], ['Weight', '≈ 14 kg']] },
  'head.valvesIn': { name: 'Intake valves', qty: '8', mat: 'Titanium alloy',
    role: 'Open the way for fresh mixture into the cylinder on the intake stroke.',
    how: 'The valve head seats on the valve seat and seals the cylinder. The cam lobe opens the valve and the spring closes it. Light titanium lets the valve follow the cam at high rpm. Intake valves are larger than exhaust valves because the mixture needs more flow area.',
    data: [['Head diameter', '37 mm'], ['Stem diameter', '6 mm'], ['Lift', '11.5 mm']] },
  'head.valvesEx': { name: 'Exhaust valves', qty: '8', mat: 'Nickel-based heat-resistant alloy',
    role: 'Let the burnt gas out of the cylinder into the exhaust manifold.',
    how: 'They work in the harshest conditions: gas at up to 900 °C sweeps over the valve head. Heat leaves through the seat and guide into the cooled head. The valve opens before the piston reaches bottom dead centre so the cylinder pressure has time to drop.',
    data: [['Head diameter', '32 mm'], ['Lift', '11.5 mm'], ['Head temperature', 'up to 800–900 °C']] },
  'head.springs': { name: 'Valve springs', qty: '16', mat: 'Silicon-chrome steel, shot-peened',
    role: 'Close the valve and keep the valvetrain against the cam so the valve follows the lobe exactly.',
    how: 'A retainer and two collets hold the spring on the valve stem. At 7,500 rpm each valve opens and closes 62 times a second: a weak spring would let the valve float and meet the piston.',
    data: [['Seat load', '≈ 400 N'], ['Load at full lift', '≈ 1,000 N']] },
  'head.tappets': { name: 'Tappets', qty: '16', mat: 'Steel, diamond-like coating',
    role: 'Pass the cam force to the valve stem and take the side load.',
    how: 'A bucket tappet slides in a bore in the head. Valve clearance is set with a calibrated shim. Without hydraulic lifters the valvetrain is lighter and stiffer, which matters at high rpm.',
    data: [['Diameter', '31 mm'], ['Valve clearance', '0.20–0.30 mm']] },
  'head.camIn': { name: 'Intake camshaft', qty: '1', mat: 'Alloy steel, induction-hardened',
    role: 'Opens and closes the intake valves of the bank in step with the pistons.',
    how: 'The camshaft turns at half crankshaft speed: over two crank revolutions (one full cycle) each valve opens once. The lobe shape sets when the valve opens, for how long and how far, and it largely defines the character of the engine.',
    data: [['Opens', '30° before TDC'], ['Closes', '60° after BDC'], ['Duration', '270° crank'], ['Valve lift', '11.5 mm']] },
  'head.camEx': { name: 'Exhaust camshaft', qty: '1', mat: 'Alloy steel, induction-hardened',
    role: 'Controls the exhaust valves of the bank.',
    how: 'The exhaust opens 70° before bottom dead centre, while cylinder pressure is still high, so the gas blows out on its own. It closes after top dead centre, with the intake already open: during this overlap the exhaust flow helps draw in fresh mixture.',
    data: [['Opens', '70° before BDC'], ['Closes', '30° after TDC'], ['Duration', '280° crank'], ['Overlap', '60°']] },
  'head.camCaps': { name: 'Camshaft bearing caps', qty: '5', mat: 'Aluminium alloy',
    role: 'Hold the camshafts in their bearings in the head.',
    how: 'Each cap is machined together with the head, so it fits only in its own place and orientation. Pressurised oil reaches the camshaft journals through the bearings.',
    data: [['Fastening', '4 bolts per cap'], ['Camshaft journals', 'Ø26 mm']] },
  'head.bolts': { name: 'Cylinder head bolts', qty: '10', mat: 'High-strength chrome-molybdenum steel',
    role: 'Clamp the head to the block through the gasket hard enough that gas cannot escape.',
    how: 'They are tightened in several stages from the centre outwards to a set torque and angle. The long bolt stretches like a spring and keeps its clamp load through heat cycles and firing pressure.',
    data: [['Thread', 'M11 × 1.5'], ['Clamp load', '≈ 80 kN per bolt']] },
  'head.plugs': { name: 'Spark plugs', qty: '4', mat: 'Iridium electrode, ceramic insulator',
    role: 'Ignite the mixture in the combustion chamber at precisely the calculated moment.',
    how: 'High voltage from the coil jumps the gap between the electrodes. Racing plugs are "cold": they shed heat quickly into the head so the electrode does not overheat and ignite the mixture before the spark. The fine iridium electrode gives a stable spark.',
    data: [['Thread', 'M10 × 1.0'], ['Gap', '0.6 mm'], ['Breakdown voltage', 'up to 35 kV']] },
  'head.cover': { name: 'Cam cover', qty: '1', mat: 'Carbon fibre, twill weave',
    role: 'Covers the valvetrain, keeps the oil in and the dirt out.',
    how: 'The cover is laid up from carbon cloth in epoxy: several times lighter than aluminium and happy at head temperature. A seal runs around the edge and wells in the centre take the ignition coils.',
    data: [['Weight', '≈ 0.7 kg'], ['Process', 'prepreg, autoclave']] },
  'head.coils': { name: 'Ignition coils', qty: '4', mat: 'Plastic housing, epoxy potting',
    role: 'Turn the 14 V supply into tens of kilovolts for the spark.',
    how: 'Each coil sits directly on its spark plug: no high-tension leads, losses or interference. The control unit charges the coil for a few milliseconds and cuts the current at the ignition point, inducing a high-voltage pulse in the secondary winding.',
    data: [['Output voltage', 'up to 40 kV'], ['Dwell time', '≈ 2–3 ms']] },

  'intake.trumpets': { name: 'Intake trumpets', qty: '8', mat: 'Composite',
    role: 'Guide air smoothly into the intake tract and set its tuned length.',
    how: 'The rounded lip reduces entry losses. The trumpet length together with the runner and port is chosen so that the reflected pressure wave reaches the valve as it opens, giving a small boost without a supercharger in the target rpm range.',
    data: [['Lip diameter', '≈ 80 mm'], ['Tract length to valve', '≈ 280 mm']] },
  'intake.throttles': { name: 'Throttle bodies', qty: '2 (4 butterflies each)', mat: 'Aluminium alloy, anodised',
    role: 'Control the amount of air, and therefore the engine output.',
    how: 'Each cylinder has its own butterfly in its own bore. The butterfly is very close to the valve, so pedal movement changes cylinder filling almost instantly. All eight butterflies are synchronised on common shafts.',
    data: [['Bore', '52 mm'], ['Butterflies', '8']] },
  'intake.runners': { name: 'Intake runners', qty: '8', mat: 'Carbon fibre',
    role: 'Connect the throttle bodies to the ports in the cylinder head.',
    how: 'A smooth bend and gradual taper speed the flow towards the valve. Each runner has an injector boss. Carbon fibre is light and a poor heat conductor, so the intake air picks up less heat.',
    data: [['Section at head', 'Ø48 mm'], ['Weight', '≈ 80 g']] },
  'intake.linkage': { name: 'Throttle linkage', qty: '1 set', mat: 'Steel, aluminium',
    role: 'Transfers pedal movement to the throttle shafts of both banks.',
    how: 'Levers on the shafts are joined by an adjustable rod, so both banks open in sync. Two independent return springs close the throttles even if one of them breaks.',
    data: [['Return springs', '2, redundant']] },
  'intake.tps': { name: 'Throttle position sensor', qty: '1', mat: 'Plastic housing, contactless Hall sensor',
    role: 'Tells the control unit how far the throttles are open.',
    how: 'From throttle angle and rpm the control unit calculates cylinder filling and sets fuel and ignition. With individual throttles this is more reliable than measuring manifold vacuum.',
    data: [['Signal', '0.5–4.5 V'], ['Resolution', '≈ 0.1°']] },

  'fuel.rails': { name: 'Fuel rails', qty: '2', mat: 'Aluminium alloy, anodised',
    role: 'Distribute fuel to the injectors of each bank and smooth out pressure pulses.',
    how: 'A rail is a thick-walled tube with injector sockets. Its volume acts as an accumulator: when the injectors open the pressure hardly drops, and each gets the same amount.',
    data: [['Working pressure', '4 bar'], ['Inner diameter', '12 mm']] },
  'fuel.injectors': { name: 'Fuel injectors', qty: '8', mat: 'Solenoid valve in a steel body',
    role: 'Spray petrol into the intake runner of each cylinder.',
    how: 'The control unit opens the solenoid valve for a few milliseconds; the amount of fuel is proportional to the opening time. The nozzle breaks the jet into fine droplets that evaporate quickly in the airflow.',
    data: [['Flow rate', '≈ 650 cc/min'], ['Pulse width', '2–14 ms']] },
  'fuel.fpr': { name: 'Fuel pressure regulator', qty: '1', mat: 'Anodised aluminium, diaphragm',
    role: 'Keeps rail pressure constant and returns surplus fuel to the tank.',
    how: 'A spring presses on a diaphragm, which opens the return passage when pressure exceeds the setting. The screw on top sets the spring load. With constant pressure the injected amount depends only on injector opening time.',
    data: [['Setting', '4.0 bar'], ['Range', '2.5–6 bar']] },
  'fuel.lines': { name: 'Fuel lines and AN fittings', qty: '1 set', mat: 'Stainless-braided hoses, anodised fittings',
    role: 'Feed fuel to the rails, link the rails together and return surplus to the regulator.',
    how: 'A steel-braided hose withstands pressure and vibration and is unaffected by fuel and heat. AN fittings seal on a 37° cone without gaskets and can be taken apart many times.',
    data: [['Size', 'AN-6, ≈ 8 mm bore'], ['Seal', '37° cone']] },

  'exh.flange': { name: 'Manifold flange', qty: '1', mat: 'Stainless steel',
    role: 'Clamps the manifold pipes to the cylinder head and carries the whole assembly.',
    how: 'The thick machined flange does not warp when heated to hundreds of degrees, so the joint to the head stays sealed. The pipes are welded in from behind so the weld does not disturb the flow.',
    data: [['Thickness', '8 mm'], ['Fastening', '8 × M8 studs']] },
  'exh.primaries': { name: 'Primary pipes', qty: '4', mat: 'Titanium, 0.9 mm wall',
    role: 'Carry the gas from each cylinder to the collector.',
    how: 'Pipe length and diameter are tuned to the working rpm range: the low-pressure wave reflected from the collector returns to the valve during overlap and helps pull out the remaining gas. The heat tint near the flange is the mark of hot titanium.',
    data: [['Diameter', '44 mm'], ['Tuned for', '6,000–7,500 rpm'], ['Gas temperature', 'up to 900 °C']] },
  'exh.collector': { name: '4-into-1 collector', qty: '1', mat: 'Titanium',
    role: 'Merges the four primary pipes into one.',
    how: 'The pipes meet at a shallow angle and the cone accelerates the flow smoothly. Each exhaust pulse passing through the collector creates low pressure in the neighbouring pipes, which helps scavenge the cylinders. A V-band clamp at the outlet allows quick removal.',
    data: [['Outlet diameter', '76 mm'], ['Joint', 'V-band clamp']] },
  'exh.lambda': { name: 'Lambda sensor', qty: '1', mat: 'Zirconia ceramic in a steel body',
    role: 'Measures the oxygen in the exhaust, which shows the mixture strength.',
    how: 'A wideband sensor gives the exact air–fuel ratio. Fuel maps are tuned with it: at full power the mixture is kept slightly rich (λ ≈ 0.88) to cool the chamber and protect the pistons.',
    data: [['Type', 'wideband, 5-wire'], ['Operating temperature', '≈ 750 °C']] },
  'exh.studs': { name: 'Studs and nuts', qty: '8', mat: 'Heat-resistant steel, copper-plated nuts',
    role: 'Fasten the manifold flange to the head.',
    how: 'The studs stay in the head and the nuts go on from outside, so the aluminium threads are not disturbed at every removal. Copper plating stops the nuts seizing from heat.',
    data: [['Thread', 'M8 × 1.25'], ['Torque', '≈ 22 N·m']] },

  'timing.cover': { name: 'Front cover', qty: '1', mat: 'Aluminium alloy, casting',
    role: 'Encloses the camshaft chain drive, keeps the oil in and carries the water pump and accessories.',
    how: 'The water pump volute, crankshaft seal and cam sensor bosses are built into the cover. Bolts all round the edge clamp it evenly to the block and heads: the joint must stay dry at any temperature.',
    data: [['Bolts', '≈ 30'], ['Weight', '≈ 4.5 kg']] },
  'timing.chains': { name: 'Camshaft drive chains', qty: '2', mat: 'Alloy steel',
    role: 'Transfer rotation from the crankshaft to the camshafts of each bank.',
    how: 'The chain barely stretches over its life and runs in oil, so the valve timing does not drift. The cam sprockets are twice the size of the drive sprocket: for two crank revolutions the camshaft makes one.',
    data: [['Pitch', '8 mm'], ['Ratio', '2 : 1']] },
  'timing.camSprockets': { name: 'Camshaft sprockets', qty: '4', mat: 'Steel, hardened',
    role: 'Take the drive from the chain and turn the camshafts.',
    how: 'The sprocket is located on the shaft by a dowel and central bolt, so its position relative to the lobes is fixed. On racing engines the sprockets have slotted holes for fine timing adjustment.',
    data: [['Teeth', '36'], ['Pitch diameter', '≈ 92 mm']] },
  'timing.crankSprocket': { name: 'Crankshaft drive sprocket', qty: '1 (double)', mat: 'Steel, hardened',
    role: 'Drives both camshaft chains from the nose of the crankshaft.',
    how: 'Two rows of teeth on one hub, one for each bank’s chain. The sprocket is keyed to the crank, so crankshaft and camshaft positions are locked together.',
    data: [['Teeth', '2 × 18'], ['Mounting', 'key and central bolt']] },
  'timing.guides': { name: 'Chain guides and tensioner shoes', qty: '4', mat: 'Polyamide on a steel backing',
    role: 'Guide the chains and damp their side-to-side motion.',
    how: 'A fixed guide sits on the tight side, a pivoting shoe pushed by the tensioner on the slack side. The polyamide sliding face runs in oil with almost no wear.',
    data: [['Sliding face', 'polyamide'], ['Per chain', '2']] },
  'timing.tensioners': { name: 'Hydraulic chain tensioners', qty: '2', mat: 'Aluminium body, steel plunger',
    role: 'Keep the chains at constant tension.',
    how: 'The plunger is pushed out by a spring and by oil pressure from the lubrication system. A check valve stops it retreating quickly, so the chain does not slap when rpm changes suddenly.',
    data: [['Plunger travel', '≈ 12 mm'], ['Supply', 'engine oil pressure']] },
  'timing.camSensors': { name: 'Camshaft position sensors', qty: '2', mat: 'Hall sensor in a plastic housing',
    role: 'Tell the control unit which stroke each cylinder is on.',
    how: 'The crankshaft turns twice per cycle, so its sensor alone cannot tell compression from exhaust. Marks on the camshafts resolve this, and the control unit knows exactly when to inject and fire each cylinder.',
    data: [['Type', 'Hall effect'], ['Marks per shaft', '4']] },

  'front.damper': { name: 'Torsional vibration damper', qty: '1', mat: 'Steel, elastomer',
    role: 'Damps crankshaft torsional vibration and drives the accessory belt.',
    how: 'Firing pulses twist the crankshaft like a spring, and at certain speeds these oscillations can resonate strongly enough to break it. An inertia ring on an elastic layer swings out of phase and absorbs the energy. Its outer rim is the belt pulley.',
    data: [['Diameter', '164 mm'], ['Belt grooves', '6']] },
  'front.belt': { name: 'Poly-V belt', qty: '1', mat: 'Synthetic rubber, aramid cord',
    role: 'Transfers rotation from the crankshaft pulley to the alternator and water pump.',
    how: 'Longitudinal V-ribs on the inside increase the contact area with the pulleys, so the belt carries a lot of power at low tension. Its back runs over smooth idlers, so a single belt reaches every pulley.',
    data: [['Profile', 'PK, 6 ribs'], ['Width', '21 mm']] },
  'front.alternator': { name: 'Alternator', qty: '1', mat: 'Aluminium housing, copper windings',
    role: 'Generates electricity for the control unit, ignition, fuel pump and battery charging.',
    how: 'A rotor with a field winding induces alternating current in the stator; the built-in rectifier and regulator deliver a steady 14 V. The small pulley spins the alternator faster than the crankshaft, so it charges even at low rpm.',
    data: [['Output', 'up to 90 A'], ['Drive ratio', '≈ 2.7']] },
  'front.waterPump': { name: 'Water pump', qty: '1', mat: 'Aluminium housing, impeller',
    role: 'Circulates coolant through the block, heads and radiator.',
    how: 'A centrifugal impeller accelerates the coolant and sends it into the block jacket; hot coolant leaves the heads for the radiator. The pump volute is cast into the front cover.',
    data: [['Flow', '≈ 250 l/min at 7,000 rpm'], ['Drive ratio', '≈ 1.6']] },
  'front.tensioner': { name: 'Belt tensioner', qty: '1', mat: 'Aluminium arm, coil spring, bearing',
    role: 'Keeps the belt at constant tension.',
    how: 'A spring swings the arm and presses the pulley against the belt. The tensioner takes up belt stretch from heat and wear and damps snatch when rpm changes quickly.',
    data: [['Belt tension', '≈ 300 N']] },
  'front.idler': { name: 'Idler pulley', qty: '1', mat: 'Steel, sealed bearing',
    role: 'Guides the belt and increases the wrap on neighbouring pulleys.',
    how: 'The smooth pulley runs on the back of the belt. The more a pulley is wrapped, the more load it can transmit without slipping.',
    data: [['Diameter', '64 mm']] },
  'front.crankSensor': { name: 'Crankshaft position sensor', qty: '1', mat: 'Inductive sensor',
    role: 'The engine’s master sensor: reports crankshaft position and speed.',
    how: 'The sensor reads the teeth of a trigger wheel with a gap. From the gap the control unit finds top dead centre, from the pulse rate the rpm, and it times injection and spark to a fraction of a degree.',
    data: [['Trigger wheel', '60 − 2 teeth'], ['Type', 'inductive']] },

  'lube.sump': { name: 'Dry-sump pan', qty: '1', mat: 'Aluminium alloy, casting',
    role: 'Closes the crankcase from below and gathers the draining oil at the scavenge points.',
    how: 'The pan is flat, so the engine can sit lower and the car’s centre of gravity drops. Baffles and pickups in each bay stop oil pooling, and the scavenge outlets come out on the side.',
    data: [['Height', '≈ 60 mm'], ['Scavenge points', '3']] },
  'lube.pump': { name: 'Dry-sump pump', qty: '1', mat: 'Aluminium sections, steel rotors',
    role: 'Scavenges oil from the crankcase to the tank and feeds it from the tank into the engine under pressure.',
    how: 'Four rotor stages share one shaft: three scavenge and one pressure. Together the scavenge stages move several times more than the pressure stage delivers, so the crankcase holds no excess oil and runs at a slight vacuum: less windage loss and better ring sealing.',
    data: [['Stages', '1 pressure + 3 scavenge'], ['Oil pressure', '5–6 bar']] },
  'lube.drive': { name: 'Oil pump drive', qty: '1 set', mat: 'Toothed belt with aramid cord, aluminium pulleys',
    role: 'Drives the oil pump from the crankshaft.',
    how: 'The toothed belt cannot slip, so pump delivery always follows rpm. The pump pulley is larger than the drive pulley: the pump turns at about 0.6 of crank speed and the rotors do not cavitate.',
    data: [['Ratio', '≈ 0.6'], ['Belt profile', 'HTD, 8 mm pitch']] },
  'lube.lines': { name: 'Scavenge lines', qty: '1 set', mat: 'Steel-braided hoses, AN fittings',
    role: 'Connect the sump scavenge points to the pump stages.',
    how: 'Scavenge lines are larger than the pressure line because they carry crankcase gas and foam along with the oil. Cone-seal fittings do not leak under vibration.',
    data: [['Scavenge', 'AN-12'], ['Pressure', 'AN-10']] },
  'lube.filter': { name: 'Oil filter', qty: '1', mat: 'Steel canister, synthetic element',
    role: 'Cleans wear debris out of the oil before it reaches the bearings.',
    how: 'Oil passes through the pleated element from outside in. If the element clogs, a bypass valve lets oil around it: poorly filtered oil is better than none.',
    data: [['Filtration', '≈ 20 µm'], ['Bypass valve', '≈ 1 bar']] },
  'lube.sender': { name: 'Oil pressure sensor', qty: '1', mat: 'Piezoresistive sensor',
    role: 'Continuously measures oil pressure in the main gallery.',
    how: 'A pressure drop is the first sign of trouble: oil starvation in a corner, a leak or bearing wear. The data logger records the pressure and warns the driver if it falls dangerously.',
    data: [['Range', '0–10 bar']] },

  'clutch.flywheel': { name: 'Flywheel', qty: '1', mat: 'Steel, lightened',
    role: 'Carries the clutch pack and the starter ring gear and smooths out rotation.',
    how: 'A racing flywheel is light and small, so the engine gains and loses revs quickly. The multi-plate clutch makes up for the small friction area.',
    data: [['Diameter', '184 mm'], ['Weight', '≈ 3 kg']] },
  'clutch.discs': { name: 'Driven plates', qty: '3', mat: 'Sintered-metal facings on steel',
    role: 'Transfer torque from the flywheel to the gearbox input shaft.',
    how: 'The plates ride on the gearbox shaft splines. Three plates give six friction faces, so a small clutch carries the full engine torque with margin. Sintered facings survive the heat of race starts.',
    data: [['Diameter', '140 mm'], ['Friction faces', '6']] },
  'clutch.plates': { name: 'Intermediate plates', qty: '2', mat: 'Steel',
    role: 'Separate the driven plates and turn with the flywheel.',
    how: 'Tabs on the outer edge engage slots in the cover: the plates turn with the flywheel but can slide axially when the clutch is released.',
    data: [['Thickness', '≈ 3 mm']] },
  'clutch.cover': { name: 'Clutch cover', qty: '1', mat: 'Aluminium alloy, steel diaphragm spring',
    role: 'Clamps the plate pack and releases it when the pedal is pressed.',
    how: 'A diaphragm spring clamps the pack through the pressure plate. The release bearing presses on its fingers, the spring flexes and frees the plates, disconnecting the engine from the gearbox.',
    data: [['Clamp load', '≈ 6 kN']] },
  'clutch.bolts': { name: 'Flywheel and cover bolts', qty: '14 (8 + 6)', mat: 'High-strength steel',
    role: 'Fasten the flywheel to the crankshaft flange and the cover to the flywheel.',
    how: 'The flywheel bolts take every driveline shock, so they are torqued under control and secured with anaerobic thread locker.',
    data: [['Flywheel bolts', '8 × M10'], ['Cover bolts', '6 × M8']] },

  'elec.ecu': { name: 'Engine control unit', qty: '1', mat: 'Finned aluminium case, multi-layer board',
    role: 'Controls fuel injection, ignition and the rev limit from the sensor signals.',
    how: 'Hundreds of times a second the unit reads crank and cam position, throttle angle, temperatures and mixture from the lambda sensors. Using the maps set during tuning it calculates how much fuel to inject, when, and when to fire the plug, and it logs every channel for the team’s engineers.',
    data: [['Injection channels', '8'], ['Ignition channels', '8'], ['Data logging', 'up to 1,000 times a second']] },
  'elec.harness': { name: 'Wiring loom', qty: '1 set', mat: 'Wires in heat-resistant sleeving, sealed connectors',
    role: 'Carries power and signals between the control unit, coils, injectors and sensors.',
    how: 'A racing loom is hand-built for its engine: every wire cut to length with no unnecessary joints. The sleeving resists heat and oil, and latching connectors cannot shake loose.',
    data: [['Connectors', 'sealed, latching'], ['Temperature rating', 'up to 150 °C']] },
  'elec.cts': { name: 'Coolant temperature sensor', qty: '1', mat: 'Thermistor in a brass body',
    role: 'Reports engine temperature to the control unit.',
    how: 'The thermistor’s resistance changes with temperature. On a cold engine the control unit richens the mixture; on overheating it warns the driver and can limit power.',
    data: [['Range', '−40…150 °C'], ['Type', 'NTC thermistor']] },

  'ext.tank': { name: 'Oil tank', qty: '1', mat: 'Welded aluminium alloy',
    role: 'Stores the oil for the dry-sump system and removes air from it.',
    how: 'The scavenge stages return oil to the tank along with foam. Inside, the oil swirls round the wall, air escapes upwards through the breather, and dense bubble-free oil reaches the pickup at the bottom. A tall narrow tank keeps the pickup covered in corners.',
    data: [['Capacity', '≈ 10 l'], ['Breather', 'in the top cap']] },
  'ext.tankLines': { name: 'Oil tank lines', qty: '1 set', mat: 'Steel-braided hoses, AN fittings',
    role: 'Feed oil from the tank to the pressure stage of the pump and return scavenged oil to the tank.',
    how: 'The feed line is short and large so the pump never starves at high rpm. The return enters the top of the tank tangentially and swirls the flow to help separate air.',
    data: [['Feed', 'AN-12'], ['Return', 'AN-10']] },
  'ext.radiator': { name: 'Radiator', qty: '1', mat: 'Aluminium: flat tubes and corrugated fins',
    role: 'Passes coolant heat to the oncoming air.',
    how: 'Hot coolant from the heads flows through thin flat tubes with corrugated fins brazed between them. The airflow carries the heat away and the cooled liquid returns to the water pump. The cap holds about 1.5 bar so the coolant does not boil. On the stand the hose necks are capped.',
    data: [['Working pressure', '≈ 1.5 bar'], ['Coolant temperature', '85–100 °C']] },
};
